---
# tasks file for roles/applications/jmeter_kubernetes

- name: Define payload values
  set_fact:
    payloadValues: ["60","1024","2048","10240","102400","1048576"]
#    payloadValues: ["60","1024"]

- name: Export mosquitto service name on server
  become: yes
  shell: |
    echo "
    apiVersion: clusterlink.net/v1alpha1
    kind: Export
    metadata:
      name: mosquitto-cluster
      namespace: default
    spec:
      port: 1883
    " | kubectl apply -f -
  delegate_to: "{{ groups['headnodes'][0] }}"

- name: Export rabbitmq service name on server
  become: yes
  shell: |
    echo "
    apiVersion: clusterlink.net/v1alpha1
    kind: Export
    metadata:
      name: rabbitmq-cluster
      namespace: default
    spec:
      port: 5672
    " | kubectl apply -f -
  delegate_to: "{{ groups['headnodes'][0] }}"

- name: Export zenoh service name on server
  become: yes
  shell: |
    echo "
    apiVersion: clusterlink.net/v1alpha1
    kind: Export
    metadata:
      name: zenoh-cluster
      namespace: default
    spec:
      port: 7447
    " | kubectl apply -f -
  delegate_to: "{{ groups['headnodes'][0] }}"

- name: Import mosquitto service on clients
  become: yes
  shell: |
    echo "
    apiVersion: clusterlink.net/v1alpha1
    kind: Import
    metadata:
      name: mosquitto-cluster
      namespace: default
    spec:
      port: 1883
      sources:
        - exportName: mosquitto-cluster
          exportNamespace: default
          peer: cluster{{  hostvars[groups['headnodes'][0]].cluster }}
    " | kubectl apply -f -
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

- name: Import rabbitmq service on clients
  become: yes
  shell: |
    echo "
    apiVersion: clusterlink.net/v1alpha1
    kind: Import
    metadata:
      name: rabbitmq-cluster
      namespace: default
    spec:
      port: 5672
      sources:
        - exportName: rabbitmq-cluster
          exportNamespace: default
          peer: cluster{{  hostvars[groups['headnodes'][0]].cluster }}
    " | kubectl apply -f -
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

- name: Import zenoh service on clients
  become: yes
  shell: |
    echo "
    apiVersion: clusterlink.net/v1alpha1
    kind: Import
    metadata:
      name: zenoh-cluster
      namespace: default
    spec:
      port: 7447
      sources:
        - exportName: zenoh-cluster
          exportNamespace: default
          peer: cluster{{  hostvars[groups['headnodes'][0]].cluster }}
    " | kubectl apply -f -
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

- name: Allow all communication
  become: yes
  shell: |
    echo "
    apiVersion: clusterlink.net/v1alpha1
    kind: AccessPolicy
    metadata:
      name: allow-policy
      namespace: default
    spec:
      action: allow
      from:
      - workloadSelector: {}
      to:
      - workloadSelector: {}
    " | kubectl apply -f -
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host

- name: Create benchmarking pod
  become: yes
  shell: |
    echo "
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jmeter-data-volume
      namespace: default
      labels:
        type: local
    spec:
      storageClassName: manual
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
      claimRef:
         namespace: default
         name: jmeter-data-claim
      hostPath:
        path: "/tmp/benchfaster"
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - worker
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: jmeter-data-claim
      namespace: default
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: benchmark-deployment
      labels:
        app: benchmark-pod
    spec:
      selector:
        matchLabels:
          app: benchmark-pod
      template:
        metadata:
          labels:
            app: benchmark-pod
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: worker
          containers:
            - name: benchmark-pod
              image: registry.gitlab.com/m4rl4/brokerperformance:latest
              imagePullPolicy: Always
              command: ['/bin/sh', '-c', 'sleep infinity']
              volumeMounts:
                - mountPath: "/tmp/benchfaster"
                  name: jmeter
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "2000m"
          volumes:
            - name: jmeter
              persistentVolumeClaim:
                claimName: jmeter-data-claim
          terminationGracePeriodSeconds: 0
    " | kubectl apply -f -
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

- name: Wait for benchmark pod to become ready
  become: yes
  shell: kubectl rollout status deployment benchmark-deployment
  retries: 10
  delay: 5
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

- name: log the current latency to the nebula lighthouse
  become: yes
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- bash -c "/usr/bin/ping -c 4 {{ address_benchmark }} | tee {{ results_path.path }}/latency_nebula_{{ network.name }}.chk"
  delegate_to: "{{ groups['headnodes'][1] }}"

- name: Test mosquitto for functionality through clusterlink
  become: yes
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- nc -zv mosquitto-cluster 1883
  retries: 3
  delay: 5
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

- name: Test rabbitmq for functionality through clusterlink
  become: yes
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- nc -zv rabbitmq-cluster 5672
  retries: 3
  delay: 5
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

- name: Test zenoh for functionality through clusterlink
  become: yes
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- nc -zv zenoh-cluster 7447
  retries: 3
  delay: 5
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
  when:
    - "current_host != groups['headnodes'][0]"

#TODO: update parameter values
- name: Test Mosquitto directly
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- python /opt/brokertestingwithlogging.py --payload {{ payloadSize }} \
      -m {{ address_benchmark }}:31883 \
      --warm-up 5 \
      -o {{ results_path.path }}/mosquitto_{{ payloadSize }}_direct_{{ network.name }}.csv
  delegate_to: "{{ groups['headnodes'][1] }}"
  loop: "{{ payloadValues }}"
  loop_control:
    loop_var: payloadSize

- name: Test RabbitMQ directly
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- python /opt/brokertestingwithlogging.py --payload {{ payloadSize }} \
      -r {{ address_benchmark }}:30672 \
      --warm-up 5 \
      -o {{ results_path.path }}/rabbitmq_{{ payloadSize }}_direct_{{ network.name }}.csv
  delegate_to: "{{ groups['headnodes'][1] }}"
  loop: "{{ payloadValues }}"
  loop_control:
    loop_var: payloadSize

- name: Test Zenoh directly
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- python /opt/brokertestingwithlogging.py --payload {{ payloadSize }} \
      -z {{ address_benchmark }}:31447 \
      --warm-up 5 \
      -o {{ results_path.path }}/zenoh_{{ payloadSize }}_direct_{{ network.name }}.csv
  delegate_to: "{{ groups['headnodes'][1] }}"
  loop: "{{ payloadValues }}"
  loop_control:
    loop_var: payloadSize

- name: Test Mosquitto through clusterlink
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- python /opt/brokertestingwithlogging.py --payload {{ payloadSize }} \
      -m mosquitto-cluster:1883 \
      --warm-up 5 \
      -o {{ results_path.path }}/mosquitto_{{ payloadSize }}_clusterlink_{{ network.name }}.csv
  delegate_to: "{{ groups['headnodes'][1] }}"
  loop: "{{ payloadValues }}"
  loop_control:
    loop_var: payloadSize

- name: Test RabbitMQ through clusterlink
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- python /opt/brokertestingwithlogging.py --payload {{ payloadSize }} \
      -r rabbitmq-cluster:5672 \
      --warm-up 5 \
      -o {{ results_path.path }}/rabbitmq_{{ payloadSize }}_clusterlink_{{ network.name }}.csv
  delegate_to: "{{ groups['headnodes'][1] }}"
  loop: "{{ payloadValues }}"
  loop_control:
    loop_var: payloadSize

- name: Test Zenoh through clusterlink
  shell: |
    kubectl exec -i deploy/benchmark-deployment -- python /opt/brokertestingwithlogging.py --payload {{ payloadSize }} \
      -z zenoh-cluster:7447 \
      --warm-up 5 \
      -o {{ results_path.path }}/zenoh_{{ payloadSize }}_clusterlink_{{ network.name }}.csv
  delegate_to: "{{ groups['headnodes'][1] }}"
  loop: "{{ payloadValues }}"
  loop_control:
    loop_var: payloadSize

#- name: Test hello-world for functionality through external connection
#  become: yes
#  shell: |
#    kubectl exec -i deploy/benchmark-deployment -- curl http://hello-world.default.{{ address_benchmark }}.nip.io
#  retries: 3
#  delay: 5
#  delegate_to: "{{ current_host }}"
#  loop: "{{ groups['headnodes'] }}"
#  loop_control:
#    loop_var: current_host
#  when:
#    - "current_host != groups['headnodes'][0]"
#    - "directbenchmark | bool"

#- name: Fail intentionally
#  become: yes
#  shell: /bin/false
#  delegate_to: "{{ groups['headnodes'][0] }}"
