- name: Apply intra-cluster netem set "{{ netem.name }}" (Machines)
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
  args:
    apply:
      delegate_to: "{{ hitem }}"
  vars:
    netem: "{{ network.intra }}"
  loop: "{{ groups['workers'] }}"
  loop_control:
    loop_var: hitem

- name: Apply intra-cluster netem set "{{ netem.name }}" (Headnode)
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
  args:
    apply:
      delegate_to: "{{ hitem }}"
  vars:
    netem: "{{ network.intra }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: hitem

- name: Apply inter-cluster netem set "{{ netem.name }}" (Machines)
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
  args:
    apply:
      delegate_to: "{{ hitem }}"
  vars:
    netinterface: nebula
    netem: "{{ network.inter }}"
  loop: "{{ groups['workers'] }}"
  loop_control:
    loop_var: hitem

- name: Apply inter-cluster netem set "{{ netem.name }}" (Headnode)
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
  args:
    apply:
      delegate_to: "{{ hitem }}"
  vars:
    netinterface: nebula
    netem: "{{ network.inter }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: hitem

#- name: Apply netem set "{{ netem.name }}" (Testers)
#  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
#  args:
#    apply:
#      delegate_to: "{{ hitem }}"
#  loop: "{{ groups['testers'] }}"
#  loop_control:
#    loop_var: hitem
