- ansible.builtin.include_role:
    name: "{{ role_item }}"
  with_items:
    - benchfaster/start-multi-cluster
    - benchfaster/registry-add
    - applications/skupper
    - applications/mosquitto
    - applications/rabbitmq
    - applications/zenoh
    - applications/brokers_skupper
    - benchfaster/stop
  loop_control:
    loop_var: role_item
