- name: Install machine requirements
  hosts: machines
  tasks:

    - name: Install requirements (Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
        - bc
        - rsync
        - sudo
        - curl
        - jq
        - libreswan
        - wget
        - git
        - podman
        - wireguard
        update_cache: no
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu" or ansible_facts['distribution']=="Debian"

    - name: Install requirements (Archlinux) 
      community.general.pacman:
        name:
          - curl
          - jq
          - wget
          - git
          - podman
        update_cache: no
        state: present
      become: true
      when: ansible_facts['distribution']=="Archlinux"
